Added samba to packages installed for RedHat and Debian/Ubuntu families for smb testing
saltstack/salt-jenkins pull request #1839
Opened 2023-11-15 20:33 UTC by dmurphy18

Added samba packages to be installed on RedHat and Debian/Ubuntu families to allow for smb testing by Salt.

2023-11-15 21:14 UTC, s0undt3ch requested changes
Where's `pkgs/samba.sls` ?

2023-11-15 21:18 UTC, dmurphy18 commented
missed needing that, adding it now

2023-11-15 21:23 UTC, s0undt3ch approved these changes

2023-11-16 18:55 UTC, s0undt3ch approved these changes

2023-11-16 18:55 UTC, merged